lsi: false
safe: true
source: . 
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - 1brc-php.md
