plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
theme: jekyll-theme-minimal
title: Eksandral's stories I've never told
description: Little stories of my development life
lsi: false
safe: true
source: . 
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

relative_links:
  enabled: true
  collections: true
include:
  - 1brc-php.md
